# Generated by Django 2.0.3 on 2018-04-09 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField(blank=True, default='Shopping Cart')),
                ('status', models.TextField(choices=[('cart', 'Shopping Cart'), ('payment', 'Payment Processing'), ('sold', 'Finalized Sale')], db_index=True, default='cart')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ship_date', models.DateTimeField(blank=True, null=True)),
                ('ship_tracking', models.TextField(blank=True, null=True)),
                ('ship_name', models.TextField(blank=True, null=True)),
                ('ship_address', models.TextField(blank=True, null=True)),
                ('ship_city', models.TextField(blank=True, null=True)),
                ('ship_state', models.TextField(blank=True, null=True)),
                ('ship_zip_code', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('active', 'Active'), ('deleted', 'Deleted')], db_index=True, default='active')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantity', models.IntegerField(default=0)),
                ('extended', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.Order')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_catalog.orderitem_set+', to='contenttypes.ContentType')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('validation_code', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Order')),
            ],
        ),
        migrations.AlterField(
            model_name='productimage',
            name='filename',
            field=models.TextField(default='image_unavailable'),
        ),
    ]
