# Generated by Django 2.0.4 on 2018-04-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
